### ISSUE TITLE
Automatic Update issue

### ISSUE THREAD

**Issue by winterturtle1** [sir-wilhelm/SmartHunter#33]
I recently found this overlay but it does not seem to work properly and I do not know what I am doing wrong. When automatic updates are enabled, it sits on:
State Machine: CheckingForUpdates (411 ms) > WaitingForProcess
for forever and no overlay apears in game. When it is disabled, I get:
InvalidOperationException: Cannot process request because the process (6904) has exited.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at SmartHunter.Core.MemoryUpdater.<>c__DisplayClass20_0.<CreateStateMachine>b__20()
   at SmartHunter.Core.StateMachine`1.Update()
   at SmartHunter.Core.MemoryUpdater.Update(Object sender, EventArgs e)

**Comment by sir-wilhelm** [comment]
```
[2020-04-28 18:39:28] Started: Assembly Version: 1.5.8.1 | File Version: 1.5.8.1
[2020-04-28 18:39:29] Config.json loaded
[2020-04-28 18:39:29] en-US.json loaded
[2020-04-28 18:39:29] MonsterData.json loaded
[2020-04-28 18:39:29] PlayerData.json loaded
[2020-04-28 18:39:29] Memory.json saved
[2020-04-28 18:39:29] Default.xaml loaded
[2020-04-28 18:39:29] State Machine: None (63 ms) > DeleteOldFiles
[2020-04-28 18:39:29] State Machine: DeleteOldFiles (54 ms) > WaitingForProcess
```
is what I get when I disabled automatic updates,

WaitingForProcess means it's waiting for MHW to start. You could try relaunching the app after the game is running or running it as admin.

**Comment by sir-wilhelm** [comment]
Please post any more information that could help you with this issue.
